# Introduction

Sablefish (*Anoplopoma fimbria*) are currently managed in British Columbia (BC) as part of the Integrated Fisheries Management Plan (IFMP), under the commercial licence category K or communal commercial licence category FK.  For the past ten years (`r yr-8` to `r yr+1`), Sablefish landings by British Columbia fishermen have averaged approximately `r avgTen` metric tons annually for trap, hook and line and trawl gear.  Most of the fish in `r yr` were captured by longline hook gear (`r LonglineP`\%) and longline trap gear (`r trapP`\%).   Most of the fish in `r yr+1` were captured by longline trap gear (`r trapP2`\%) and longline hook gear (`r LonglineP2`\%).  Fisher-log records plotted in a GIS (Geographic Information Systems) show the commercial harvest of sablefish typically occurs along the steep-walled slopes off the west coast of Haida Gwaii, in complex troughs of the Queen Charlotte Sound area, and in the steep canyons and ridges off the West Coast of Vancouver Island, at depths up to 985 fathoms.  

Fishery-independent research and assessment surveys have been conducted for Sablefish since 1988 in the waters off the west coast of Haida Gwaii (formerly Queen Charlotte Islands) south to Vancouver Island.  Survey procedures have evolved over time, but each year, the surveys consisted of fishing sets using trap gear at random selected and index sites.  These surveys are used to obtain catch rate data for assessing stock abundance, gathering biological sample records, monitoring oceanographic data and collecting tag release and recapture data.  This technical report describes survey operations and summarizes the data collected from the `r setcnt` sets during the `r yr` chartered survey aboard the F/V `r boat` and the `r setcnt2` sets during the `r yr+1` chartered survey aboard the F/V `r boat2`

Historically, the traditional component of the sablefish survey included "standardized" fishing sets that were conducted within geographic boundaries named "offshore indexing localities" (1990 through 2010).   In the 1991 survey, Sablefish were tagged and released during these standardized fishing sets.  The research and assessment survey in 1995 included the addition of six new geographic boundaries named "offshore tagging localities" or areas dedicated exclusively for conducting "traditional tagging" sets.  Over the next 13 years (1995 through 2007), revisions were made to the suite of offshore tagging localities.   Commencing in 1994, the traditional component of the Sablefish survey also included standardized sets at mainland inlet localities.  In 2003, the stratified random sampling (StRS) design was introduced.  StRS sets were conducted within 2 x 2 km grid cells, nested in five depth-stratified areas along the continental shelf.  An historic overview of the design of Sablefish surveys is provided by [@Wyeth2003] and [@Wyeth2004b].  Specific details on surveys conducted from 1988 through 1993 are provided by [@Smith1996]; surveys in 1994 and 1995 by [@Downes1997]; and surveys from 1996 to 2000 by Wyeth and Kronlund [@Wyeth2003].   For the 2001 through 2006 surveys see [@Wyeth2003], [@Wyeth2004a], [@Wyeth2004b] and [@Wyeth2006], respectively.  
