# Methods

## SURVEY DESIGN

Methodology for the `r yr` and `r yr+1`  Sablefish  research and  assessment surveys employed a stratified random sampling (StRS) design component and a traditional standardized inlet component.  The standard survey protocol requires the StRS component to be completed first, fishing from South to North.  Next, the traditional inlet component must be conducted, fishing from North to South.  If weather impacts the survey plan, the inlet sites are fished before completing the northern StRS sites in order to reduce the total number of fishing days.

### STRATIFIED RANDOM SAMPLING SURVEY DESIGN COMPONENT

Since 2011, the StRS design has been conducted in all offshore survey areas. The StRS design began on the 2003 survey with the purpose of distributing tag releases at random, collecting biological samples and developing a catch-rate based index of abundance [@Wyeth2003]. It also provided an alternative design to the historic traditional offshore component of the survey (1990 to 2010) which occured at fixed locations. 

Under the StRS design the offshore survey area is partitioned into five spatial strata (S~1~ to S~5~) and three depth strata (RD~1~ to RD~3~) for a total of 15 strata (Figure \@ref(fig:figure1)). The 5 spatial strata are S~1~ (South West Coast Vancouver Island or SWCVI), S~2~ (North West Coast Vancouver Island or NWCVI), S~3~ (Queen Charlotte Sound or QCS), S~4~ (South West Coast of Haida Gwaii or SWCHG),and S~5~ (North West Coast of Haida Gwaii or NWCHG).  The three targeted depth ranges are 100-250 fathoms (RD~1~), 250-450 fathoms (RD~2~) and 450-750 fathoms(RD~3~). The area within each of the 15 strata is sectioned into 2 km x  2 km grid cells or ‘fishing blocks’ from which set locations are randomly chosen. 

From 2003 through 2005, five grid cells were randomly selected in each spatial-depth stratum. Then from 2006 through 2010, the number of grid cells randomly selected in each spatial-depth stratum were increased to six. An analysis was completed for the 2011 survey to optimize the allocation of the blocks to strata for the 2011 and 2012 survey. However, in order to lower survey costs, the number of blocks allocated to each strata were further reduced for the 2013 survey, from a total of 110 offshore blocks to 91 offshore blocks while maintaining the same relative allocation of blocks to strata. This total number of blocks has been in place on all subsequent surveys (Table \@ref(tab:table1)).  The start locations of the `r yr` survey are
shown in Figure \@ref(fig:figure2) (top), while the start locations of the `r yr+1` survey are shown in Figure \@ref(fig:figure2) (bottom).

### TRADITIONAL STANDARD SURVEY COMPONENTS

Standardized fishing sets under the traditional component of the survey have specific gear, bait, and sampling protocols. The original intent of the standardized sets was to collect catch rate data in order to index trends in abundance, tag fish and obtain biological samples. A list of the historic standardized localities and a timeline marking notable changes to these traditional components over the survey years is presented in Appendix \@ref(app:first-appendix).  

In 2010 the offshore portion of the traditional standardized survey was terminated becasue it was show that the continued use of the standardized survey, in combination with the StRS, resulted in greater frequencey fo stock assessment errors than use of just the StRS [@Cox2011]. Since then only standardized fishing sets within four mainland inlet localities have continued, including during the 2018 and 2019 survey. A string of twenty-five (25) traps were set at five specific localities in each of the following four (4) areas: Portland Inlet, Gil Island, Finlayson Channel, and Dean/Burke Channel. The geographic boundaries of these localities are shown in Figure \@ref(fig:figure1) and fished set lines shown in Figure \@ref(fig:figure3). Trap gear was deployed near the center of each of the five localities in order to avoid the steep slopes characteristic of these channels/fjords.

## VESSELS

This survey is completed using a chartered commercial fishing vessel. The 2018 survey of `r setcnt` sets was conducted aboard the 35.66 meter F/V `r boat`, skippered by `r captain`  and Mike Derry between `r dates`, `r yr`. The `r yr+1` survey of `r setcnt2` sets was conducted aboard the 25.34 meter F/V `r boat2`, skippered by Albert (Deacon) Melnychuk between `r dates2`, `r yr+1`.  Images and information about the vessels can be found at [\underline{http://marinetraffic.com}](http://marinetraffic.com)   A complete list of vessels and sets on sablefish research and assessment surveys is found in Appendix \@ref(app:second-appendix).

## FISHING GEAR

The longline trap gear consisted of a groundline resting on the ocean floor with 25 baited traps attached to beckets at 150 foot intervals along its length and 90 pound anchors at each end (Figure \@ref(fig:figure4), b). A flagpole was required for at least one end of the set to improve visibility for retrieval. The traps (Figure \@ref(fig:figure4), a) were steel frame with a bottom hoop diameter of 54 inches and covered with an North American #84 black braided nylon web of 2.75 inch mesh. The tunnels were made of green braided, knotless, 1.25 inch mesh. The traps did not include escape rings; but instead a ‘rot panel’  of # 21 cotton located above the middle ring. 

Standard bait bags (6 by 12 inches) made of 1/8 inch web with a nylon drawstring and #7 stainless trolling snaps were included with the traps. The bait methods for each survey component are listed in Table \@ref(tab:table2). 

## FISHING OPERATIONS

During normal survey fishing operations gear was deployed on alternate days and soaked between 22 and 26 hours. Prior to deploying gear the Fishing Master inspected the targeted block to ensure it was fishable and fell within the targeted depth range.  The goal was to have as much of the gear as possible within the block boundaries.  However, there are instances when a randomly chosen block cannot be fished for a variety of reasons ie. unfishable bottom, etc.  If this occurs, the survey protocol dictates that an alternate block is to be chosen after the exploration of adjacent blocks to the east or west of the original, then north and south.  If none of those blocks meet the targeted criteria, an alternate block for the same area and depth strata is randomly chosen.

Two science staff recorded information associated with the deployment of the gear. One science member was positioned in the wheelhouse and entered the required fields on the GFBioField bridge log form within the Electronic Data Acquisition System (EDAS).  The Global positioning system (GPS) and bottom sounder data were logged continuously for the duration of the survey and designated fields on the bridge log were auto-populated. Details on electronic entry of the all GFBioField forms mentioned in this document is available in the GFBio Field User Guide 2018 and [@Olsen2010]. 

A set log was filled out on the deck by the science recorder who had maximum visibility of the crew setting the traps over the stern rail.  The set log included the time and identity of the first and last buoys, anchor time, a tally of beckets and traps as well as the unique identifying numbers for any sensors deployed.

### Stratified Random Component 

Sets in StRS blocks had a targeted soak time of 24 hours with useable fishing sets hauled as early as 22 hours or as late as 26 hours. The traps were baited with 10 pounds of loose offshore Pacific Hake (*Merluccius productus*) and 2 pounds of bagged squid (Table \@ref(tab:table2)).

### Traditional Standardized Inlet Component

Fishing sets in inlet localities had a targeted soak time of 18 hours with useable fishing sets hauled between 16 hours and 20 hours.  Traps in the inlets were baited with 2 pounds of bagged squid (Table \@ref(tab:table2)). The reaon the soak times for these inlet sets is shorter than the offshore StRS sets is so that they are comparable to historic inlet sets which were based on this shorter soak time.

## CATCH PROCESSING

Sets were hauled at a speed well timed for the science crew to accurately record the catch. Two science staff were positioned on deck at the haul card station; one person recorded the catch and the other person managed the movement of baskets. In addition, the catch recorder entered the haul start and end times into the GFBioField Bridge Log.  As the groundline was hauled, each becket and trap were entered in the GFBioField Sablefish Trap Catch form. Crew members alerted the recorder about any damage to a trap (i.e. holes) which was then recorded in the GFBioField Trap Usability form.

Catch by species from each trap was sorted into baskets by the crew. Baskets were then weighed to the nearest 0.2 kg on a motion compensating scale and given a basket use code of D, A, T, L, SD or F.  Code D designated fish species as discards or commercial catch; code A allocated sablefish for age samples; code T allocated sablefish to be tagged and released; ; code L allocated fish for length samples; code SD identified sublegal sablefish discards; code F represented fish frames with amphipod or hagfish damage.  

### Sablefish Allocation Details
 
Prior to 2018, sablefish were tagged from 1/3 of the traps on StRS and 1/2 of the traps on the inlet sets. Due to high catch numbers, the survey protocol was revised in 2018 to designate ~125 sablefish to be tagged (T) from 1/3 of the traps on all sets.  When catches were high, traps targeted for tagging were spread throughout the string to avoid tagging the first 125 fish.  A biological sample was collected from the coded "A" traps with the goal of selecting 50 to 60 fish.  If CPUE was high, the new survey protocol of 2018 designated a minimal of two traps to be used for samples.  If these two traps contained more than 60 sablefish, a random process was used to select ~60 specimens.

The remaining traps were allocated to the discard category and sorted by size into either legal or sublegal discards. The SD (sublegal discards) code was added during the 2017 survey to account for the large numbers of juvenile sablefish and facilitate their quick return to the ocean. Legal discards (D) of sablefish were kept by the vessels and processed as commercial catch. 

## BIOLOGICAL SAMPLING (LWSMO)

Biological sampling were collected from sablefish, yelloweye rockfish (*Sebastes ruberrimus*), shortraker rockfish (*Sebastes borealis*) and rougheye/blackspotted rockfish (*Sebastes aleutianus/Sebastes melanostictus*) specimens on the GFBioField Fish Recording form. Measurements were electronically recorded for fork length (L), body weight (W), sex (S) and maturity level (M). Sagittal otoliths (O) were collected and stored for potential ageing by the sclerochronology laboratory.  In addition, tissue for DNA was collected from the rougheye/blackspotted rockfish complex for later species determination.  Since this complex of two distinct species [@Orr2008] have similar appearances with slight variations in colour markings and dorsal fin lengths, the sampler visually identifed each specimen as either a rougheye, blackspotted or a hybrid species.  All rockfish and legal-sized sablefish (fork length > 55 cm) that were sacrificed for biological samples were dressed, frozen, and landed as commercial catch.

Length (L) and weight (W) measurements were collected from all Pacific halibut (*Hippoglossus stenolepis*) before they were released at sea. Only the length (L) was recorded for Pacific sleeper sharks (*Somniosus pacificus*) before release.  

## SABLEFISH TAGGING

Fish destined to be tagged were transferred from the sorting area to a tagging tank.  A vessel crew member was positioned to retrieve sablefish from the tank and provide assistance with fish handling.  A science team member was stationed at the tag sample computer to record errors, injuries and ensure correct tag numbering.  A third science team member stood at the sample station and tagged fish with a Mark II Long Tagging gun loaded with Floy FD-94 T-bar anchor tags.  The tag was inserted on the left side of the fish, 1 cm below and 2-3 cm behind the anterior insertion of the first dorsal fin.  Fork length (mm to the nearest ½ cm) measurements taken on the Scantrol measuring board were electronically transferred to the GFBioField Fish Recording form. Before release, any sampling errors, injuries or damage to the fish were documented on the Fish Recording form.  Tag checks were performed systematically to ensure tag numbers on the data form matched those on the fish specimen.  

## SABLEFISH TAG RECOVERY

Any previously tagged fish brought aboard may have been treated in one of two ways.  First, sablefish with Canadian tags were re-released with a new tag and the previous tag was removed. In addition, any wounds from the old tag were recorded.  Second, sablefish with a foreign agency tag or sablefish that had sustained numerous injuries were retained for biological sampling.  For these specimens, the tag and otoliths were stored in a bar-coded vial to be scanned into the GFBioField Tag Recovery Entry form. The Department later returns those tags released by other countries. 

In previous years, re-releases of recovered tagged sablefish with the same tag occured during the survey years 1992 through 1997 and 2004.  Re-releases of recovered tagged sablefish with a new tag began in 2005. 

```{r SensorText, echo=FALSE}
   # -- determine the sets that deployed SBE and HOBO and CTD
   sense  <-  paste("select Year, SUM(SBE39) AS SBE39, SUM(HOBO) AS HOBO, ",
                    "SUM(CTD) AS CTD, SUM(CAM) AS CAM ",
                    "from dbo.Report_SBE_HOBO_IND ",
                    "group by Year having (Year =", yr,")", sep="")
   #sensor  <-  GetSQLData(sense,"Sablefish")
   sensor <-  read.csv("c:/github/surveyreport/standaloneData/methods01_hobo.csv",header=T)
   
   sense2 <-  paste("select Year, SUM(SBE39) AS SBE39, SUM(HOBO) AS HOBO, ",
                    "SUM(CTD) AS CTD, SUM(CAM) AS CAM ",
                    "from dbo.Report_SBE_HOBO_IND ",
                    "group by Year having (Year =", yr+1,")", sep="")
   #sensor2<-  GetSQLData(sense2,"Sablefish")
   sensor2<-  read.csv("c:/github/surveyreport/standaloneData/methods02_hobo2.csv",header=T)
 
```

## OCEANOGRAPHIC SENSOR DATA COLLECTION

A Sea-bird Bird SBE 39 temperature and pressure logger was placed in a protective plastic pipe and attached to the inside of the middle or end traps.  Data was successfully collected from `r sensor[1,2]` sets in `r yr` (Appendix \@ref(app:third-appendix)) and `r sensor2[1,2]` sets in `r yr+1` (Appendix \@ref(app:fourth-appendix)).  A SBE 39 was also placed in the tagging tank on hauling days to record water temperature.   

shing sets deployed with a SBE 39 recorder In order to evaluate the impact of fishing gear on benthic habitat, Nuytco autonomous camera systems and HOBO Pendant G accelerometers were attached to traps to capture images and movement (2012 through 2017).  During the `r yr` and `r yr+1` surveys, only accelerometers were deployed.  Data was successfully collected from `r sensor[1,3]` sets in `r yr` (Appendix \@ref(app:third-appendix)) and `r sensor2[1,3]` sets in `r yr+1` (Appendix \@ref(app:fourth-appendix)). Last, a single accelerometer was stationed just forward of the hauler post. 

A Concerto CTD (conductivity, temperature and depth) sensor was placed inside the middle or end traps on `r sensor[1,4]` sets in `r yr` and `r sensor2[1,4]` sets in `r yr+1`.  Data from the accelerometers, CTD sensors, SBE temperature and pressure loggers were processed after the set was complete using tools on the GFBioField Upload Sensor Data form. 

## ELECTRONIC MONITORING VIDEO DATA COLLECTION  

At the time of hauling gear, the electronic monitoring (EM) system cameras were activated by the hydraulic sensor.  Three standard analog cameras were positioned at optimal viewing angles to record survey activities.  Two cameras were stationed along the mast to record the catch as it was processed at the hopper. A third camera was stationed on the side of the wheelhouse to record the traps as they were brought over the rail. The video data from each set was reviewed by science staff the following day to provide quality control on catch data.

\clearpage
